defaults: &defaults
  api_key: abc123
  login_id: '01032142597778097119'
  login_password: 'pass1234'

development:
  <<: *defaults
  twitter:
    consumer_key: 'development_consumer_key'
    consumer_secret: 'development_consumer_secret'

test:
  <<: *defaults
  twitter:
    consumer_key: 'test_consumer_key'
    consumer_secret: 'test_consumer_secret'

production:
  <<: *defaults
  twitter:
    consumer_key: 'production_consumer_key'
    consumer_secret: 'production_consumer_secret'
